language: go

cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

script:
 - go get -d -t -v ./...
 - go install -v ./...
 - go run ./ci/run-tests.go -race -cover

after_success:
 - bash <(curl -s https://codecov.io/bash)
